[package]
name = "arceos-loader"
version = "0.1.0"
edition = "2021"
authors = ["Tianqi Fan <1310360890@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axstd = { path = "../../ulib/axstd", optional = true }
